### PR TITLE
Add "ahead/behind" calculations to the 400 page

### PR DESCRIPTION
**Pull request by thiderman**
Add a number that shows how many total kills ahead or behind we are. It's based on the current day of the year, and comes with an explanation box!

Also fixes some smaller things on the 400 page.

### CODE REVIEW

**Comment by thiderman** [comment]
Do we also want a bot command to show this? It's a pretty simple calculation that could be put into a command, I'm sure.

**Comment by zdylag** [comment]
Minor: could you include screenshots of before / after?

**Comment by thiderman** [comment]
Sure!

# Before


---

# After


---

The "pls join Discord box" is underneath the new message box; it just didn't fit in the screenshot.

**Comment by Vgr255** [comment]
I'm going to merge this right now, and we can add a command for this later! I might get to it sometime this week if no one else does.

**Pull request merged**
