### PR TITLE
add Alchemize and entropic data to the website run UI, both current a…

### PR DESCRIPTION
**Pull request by brianyee**
Adds alchemize and entropic data for potions gained on a floor

Add to both current run and run history:
This one is tested locally.

Run history:
image
image

Current run:
image
image

### CODE REVIEW

**Comment by Vgr255** [comment]
You need to update `potion_delta` on line 1215 so that the per-floor count is correct. Aside from that, great job!

**Comment by brianyee** [comment]
I'm not sure I understand what `potion_delta` represents. As the comment suggests, I'll be adding 1 to the count similar to how Entropic adds 2?

**Comment by Vgr255** [comment]
It's essentially "Potions gained - potions used/discarded", so you'd add the length of both variables to it. So if you get 6 potions from Alchemize, but used 5, then the delta would be 1. Before this change, delta would have been -5.

**Comment by Vgr255** [comment]
(And remove the workaround I put it, plus the comment, obviously)

**Comment by brianyee** [comment]
I still don't think I understand what the delta is used for, but let me know how it looks now!

**Comment by Vgr255** [comment]
They're used to keep track of the game stuff over the length of the run (for stuff like graphs): https://github.com/Vgr255/TwitchCordBot/blob/main/gamedata.py#L846-L856

**Comment by brianyee** [comment]
ah, that makes sense. Thank you

**Pull request merged**
